export const CITIES = [
  { slug: "london", name: "London", region: "Greater London" },
  { slug: "birmingham", name: "Birmingham", region: "West Midlands" },
  { slug: "manchester", name: "Manchester", region: "Greater Manchester" },
  { slug: "leeds", name: "Leeds", region: "West Yorkshire" },
  { slug: "liverpool", name: "Liverpool", region: "Merseyside" },
  { slug: "sheffield", name: "Sheffield", region: "South Yorkshire" },
  { slug: "bristol", name: "Bristol", region: "South West" },
  { slug: "newcastle", name: "Newcastle", region: "Tyne and Wear" },
  { slug: "nottingham", name: "Nottingham", region: "East Midlands" },
  { slug: "leicester", name: "Leicester", region: "East Midlands" },
  { slug: "coventry", name: "Coventry", region: "West Midlands" },
  { slug: "cardiff", name: "Cardiff", region: "South Wales" },
  { slug: "edinburgh", name: "Edinburgh", region: "Scotland" },
  { slug: "glasgow", name: "Glasgow", region: "Scotland" },
  { slug: "belfast", name: "Belfast", region: "Northern Ireland" },
  { slug: "brighton", name: "Brighton", region: "South East" },
  { slug: "reading", name: "Reading", region: "South East" },
  { slug: "southampton", name: "Southampton", region: "South East" },
  { slug: "cambridge", name: "Cambridge", region: "East of England" },
  { slug: "oxford", name: "Oxford", region: "South East" },
  { slug: "plymouth", name: "Plymouth", region: "South West" },
  { slug: "derby", name: "Derby", region: "East Midlands" },
  { slug: "wolverhampton", name: "Wolverhampton", region: "West Midlands" },
  { slug: "stoke-on-trent", name: "Stoke-on-Trent", region: "West Midlands" },
  { slug: "sunderland", name: "Sunderland", region: "North East" },
  { slug: "bradford", name: "Bradford", region: "West Yorkshire" },
  { slug: "luton", name: "Luton", region: "East of England" },
  { slug: "milton-keynes", name: "Milton Keynes", region: "South East" },
  { slug: "swansea", name: "Swansea", region: "South Wales" },
  { slug: "aberdeen", name: "Aberdeen", region: "Scotland" },
] as const;

export type City = (typeof CITIES)[number];
